# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce16a95a48c256efdaf69d4a96f8e725"
name = "wyl_store_bnglr"
application_url = "https://wylto-shopify-production-pfcaxtk5da-el.a.run.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "orders/updated" ]
  uri = "/webhooks/orders/updated"

  [[webhooks.subscriptions]]
  topics = [ "fulfillments/create" ]
  uri = "/webhooks/fulfillments/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

[access_scopes]
scopes = "read_checkouts,read_customers,read_fulfillments,read_orders,read_products"

[auth]
redirect_urls = [
  "https://wylto-shopify-production-pfcaxtk5da-el.a.run.app/auth/callback",
  "https://wylto-shopify-production-pfcaxtk5da-el.a.run.app/auth/shopify/callback",
  "https://wylto-shopify-production-pfcaxtk5da-el.a.run.app/api/auth/callback"
]